#Wohn/Esszimer + Sensor
switch:
  - platform: rest
    name: "Shelly2 Wohnzimmer"
    scan_interval: 5
    resource: http://192.168.0.100/relay/0
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true}}'
    headers:
      content-type: application/x-www-form-urlencoded
  - platform: rest
    name: "Shelly2 Esszimmer"
    scan_interval: 5
    resource: http://192.168.0.100/relay/1
    body_on: 'turn=on'
    body_off: 'turn=off'
    is_on_template: '{{ value_json.ison == true}}'
    headers:
      content-type: application/x-www-form-urlencoded
sensor:
  - platform: rest
    resource: http://192.168.0.100/status
    name: Shelly2 Wohn/Esszimmer
    value_template: '{{ value_json.meters[0]["power"]}}'
    scan_interval: 5
